name: Count Days Between Years

on:
  workflow_dispatch:
    inputs:
      start_year:
        description: 'Start Year'
        required: false
        default: '1901'
      end_year:
        description: 'End Year'
        required: false
        default: '2000'
      sunday:
        description: 'Count Sundays?'
        type: boolean
        default: true
      monday:
        description: 'Count Mondays?'
        type: boolean
        default: false
      # Add other days as needed

jobs:
  validate_input:
    runs-on: ubuntu-latest
    outputs:
      start_year: ${{ steps.set.outputs.start_year }}
      end_year: ${{ steps.set.outputs.end_year }}
    steps:
      - name: Validate years
        id: set
        run: |
          start=${{ inputs.start_year }}
          end=${{ inputs.end_year }}
          if [ "$start" -le 1900 ]; then
            echo "Start year cannot be less than 1900"
            exit 1
          fi
          if [ "$end" -lt "$start" ]; then
            echo "End year cannot be less than start year"
            exit 1
          fi
          echo "start_year=$start" >> $GITHUB_OUTPUT
          echo "end_year=$end" >> $GITHUB_OUTPUT

  count_days:
    needs: validate_input
    runs-on: ubuntu-latest
    strategy:
      matrix:
        day: [Sunday, Monday]
    if: |
      (matrix.day == 'Sunday' && inputs.sunday == 'true') ||
      (matrix.day == 'Monday' && inputs.monday == 'true')
    steps:
      - name: Count ${{ matrix.day }}s
        run: |
          counter=0
          start=${{ needs.validate_input.outputs.start_year }}
          end=${{ needs.validate_input.outputs.end_year }}
          target_day=${{ matrix.day }}
          output_file=${{ github.workspace }}/count_${{ matrix.day }}s.txt

          touch $output_file

          for year in $(seq $start $end); do
            for month in $(seq 1 12); do
              week_day=$(date -d "$year-$month-1" +'%A')
              if [ "$week_day" == "$target_day" ]; then
                ((counter++))
              fi
            done
          done

          echo "$target_day: $counter" > $output_file

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.day }}
          path: count_${{ matrix.day }}s.txt
